dataset/dataset.go, hierarchy/hierarchy.go, renderer/renderer.go
- Added error handling to the dataset api response closing
- Reordered download service auth token expected parameter position
Check this is consistent with the other clients
Anyone except me
=> Added error handling to the dataset api response closing

dataset/dataset.go
Reorder params for getting method of dataset client, all methods should now follow param order convention
Check the params are in the right order, context, tokens followed by any other param
Anyone except me
=> Reorder params to follow convention

identity/authentication.go, identity/authentication_test.go
- Updated `identity` client to ensure response body is always closed.
- Added unit tests for some missing scenarios.
- Updated client to use `github.com/ONSdigital/log.go/log`
- renamed parameter `authToken` to `serviceAuthToken` for clarity.
=> Update identity client to ensure resp body is always closed

identity/authentication.go
Added a defensive check to prevent a `nil pointer` error when closing a response if:
- The `response` is `nil` 
OR
- The `response.body` is `nil`
=> added defensive nil pointer check to closeResponse

headers/headers.go, headers/headers_test.go
Added new `headers` package to replace duplicated & inconsistent header utilities in `go-ns`.
Added functions for `Get/Set` `Collection-Id` header plus unit tests.
=> added new headers pkg as new source of truth for common request headers

headers/headers.go, headers/headers_test.go
Added new func for checking if an error is equal to `ErrHeaderNotFound` to reduce the burden on the caller. 
A fairly common pattern in Go for "expected errors" i.e. `os.IsNotExist(err error)`. Added unit tests for new functionality.
=> added helper func for checking if an error is ErrHeaderNotFound

headers/headers.go, headers/headers_test.go
- Renamed func `IsNotFound` to `IsErrNotFound`  to be clearer.
- Added negated func `IsNotErrNotFound` for convince as it read better than using `!` to negate the condition. 
- Added unit tests.
=> added additional helper func for checking header errors

health/check.go, health/check_test.go, health/health.go, health/health_test.go
Add health checker function for calling API health endpoints and it abides the healthcheck.checker interface.
Check code logic - particularly the creation of check object determined by the response from `/health` or `/healthcheck` endpoints, see [documentation](https://github.com/ONSdigital/dp/blob/master/standards/HEALTH_CHECK_SPECIFICATION.md#check-statuses)
Anyone
=> Add health checker function

health/health.go, health/health_test.go
The health package checker functionality should make a second request to `/healthcheck` endpoint if the response status code from `/health` is 401.
The reason `/health` service endpoint may return 401 instead of a 404 is due to whitelisting endpoints for authentication. Current services will not have a `/health` endpoint and if instances of a service are in publishing state they will return a 401 over a 404 for an endpoint that doesn't exist.
* Code changes make logical sense and cover the ###What statement above
* Check unit tests still pass
Anyone
=> Handle 401 errors returning from `/health`

dataset/dataset.go
- Added missing states, according to dataset-api swagger spec
- extra state (not present in swagger) 'submitted', as required by dp-import-tracker
Anyone
=> Added missing states

dataset/data.go, dataset/dataset.go, dataset/dataset_test.go
- Implemented methods (migrated from dp-dimension-importer):
- GetInstanceDimensions
- PutInstanceDimensionOptionNodeID
- Unit tested, andadded mock constructor
- Modified models. There was a name clash for `Dimensions`. Renamed the existing to `VersionDimension`
- Unit tests pass
Anyone
=> GetInstanceDimensions, PutInstanceDimensionOptionNodeID

zebedee/client.go, zebedee/client_test.go, zebedee/data.go
This PR adds a new method, `GetHomepageContent`, and new models (`HomepageContent`) to the Zebedee client. This is so that homepage content, in particular the new `featuredContent` section can be loaded in via the homepage controller and into the renderer.
- Check that the code implemented in the method make sense, is idiomatic, and aligns with how other methods are written in the client
- Check that the test case makes sense and passes
- Check that the URI for the homepage content is correct
- Check the models and whether anything may be excluded or ought to be included that is currently missing from them; the structure is largely aligning with what is in the homepage's `data.json`, although with no `sections` array as this is now handled by the `GetTimeseriesMainFigure` method
Anyone …
=> Add getHomepageContent method to Zebedee Client

image/image.go, image/image_test.go
Implemented ImportDownloadVariant in image client, to call endpoint `POST /images/{id}/downloads/{variant}/import`
Anyone
=> Implement ImportDownloadVariant

image/image.go, image/image_test.go, zebedee/client_test.go
Add POST images/…/upload to image-api client
(Also fix another test for the zebedee client so it doesn't try to listen on an external interface, hence triggering the Mac firewall popup)
Ensure a client function fo `POST /images/{id}/upload` has been added.
Ensure unit tests pass and cover functionality.
Anyone but me
=> Add POST images/…/upload to image-api client

site-search/data.go, site-search/response_mocks/empty_results.json, site-search/response_mocks/results.json, site-search/site-search.go, site-search/site-search_test.go
- Create `site-search` client based on `dp-search-query`
- Added tests for the functionalities in the `site-search` directory
- Add example results to assist the tests
- Add `data.go` file which has the model of the essential data returned from the `dp-search-query`
- Check If the tests are successful
- Check if the code makes sense (it is very similar to the `search` and `image` directories so you can use that as a guide)
Anyone - Justin made the changes
=> add new 'site-search' dir for client from dp-search-query

README.md, health/README.md, health/health.go, image/image.go, image/image_test.go
We want to have the capability to re-use a dp-net/http Clienter among different API clients. In this PR, there is the suggested implementation in Image API client, that all clients should follow.
- Make sure that the new constructor function in ImageAPI and Health clients allows a Clienter to be reused
- Check if the changes in the README are clear
Anyone
=> Investigate re-usage of Clienters among different API clients.

codelist/codelist.go, codelist/data.go, codelist/data_test.go
Use correct value for code list code
- The ID field no longer exists on the root of the response. Use Code instead.
Review changes
@jondewijones
=> Use correct value for code list code

image/data.go, image/image.go, image/image_test.go
Add POST /images/{id}/downloads to image api client.
- Add `NewImageDowload` model
- Add `PostDownloadVariant` function to client
- Add appropriate tests
Also…
- Tidy up order of other models to match swagger spec in `dp-image-api`
- Fix issue with PostImage function expecting a 200(OK) response from the API instead of 201(Created).
- Add `State` to `NewImage` model
Ensure expected changes have been made and that appropriate tests are present.
Anyone but me
=> Add POST /images/{id}/downloads to image api client

hierarchy/hierarchy.go
Added public constructor for ErrInvalidHierarchyAPIResponse. This enables code using this library to create an instance of this error type. This is required when unit test code that uses the additional fields provided by this err type.
=> added public constructor for ErrInvalidHierarchyAPIResponse

site-search/data.go
- Change the struct `contentType` to be an exporter `ContentType`
- This is needed because this struct is needed to be available in the `dp-frontend-search-controller` to combine the count of search results on a query based on each filter type. 
- Check if the code makes sense
Anyone - Justin made the changes
=> change contentType struct to be exporter

search/search.go, search/search_test.go
When `Dimension` method is called, the URL assigned should start with `/dimension-search` instead `/search`
Therefore, the `URL` has been changed to use `/dimension-search`  
The tests have been added to use the new endpoint
Check if the change has been made correctly (a very small change)
Check if the tests pass
Anyone - Justin made the changes
=> update dimension search endpoint

dataset/data.go, dataset/dataset.go, dataset/dataset_test.go, filter/data.go, filter/filter.go, filter/filter_test.go
- Modified dataset API client to support pagination for getOptions:
- add limit and offset query params
- modified returned model to include limit, offset, count and total count
Anyone
=> dataset GetOptions with offset and limit

filter/data.go, filter/filter.go, filter/filter_test.go
- Introduced Dimensions struct in filter client, to match the paginated response from filter API
- Used this struct as the return type for filter.GetDimensions
- changed unit tests accordingly
- Use QueryParams struct to provide offset and limit to `GetDimensionOptions` and `GetDimensions`
Anyone
=> filter GetDimensions response is now mapped to the paginated struct

dataset/dataset.go, dataset/dataset_test.go
-Bug fix: replaced query parameter to filter by id from `ids` to `id`
- Make sure the `ids` query param key has been replaced with `id` (sanity check)
Anyone
=> fixed wrong query parameter key (id instead of ids)

zebedee/client.go
Timeout and maximum retries can now be set in the new constructor
Currently, there is an insane number of retries between the dp-frontend-router and Zebedee. From client level, web server level and platform level. As such we are able to remove the client level retries. Requests that are failing are staying open too long and this is hindering the dp-frontend-routers performance to the point it causes fall overs. This PR should help to address these issues in conjunction with other improvements.
In dp-frontend-router or another service that uses this client run:
go mod edit -replace github.com/ONSdigital/dp-api-clients-go=/{path to your local dp-api-clients-go}
Replacing the {path to your local dp-api-clients-go} with your local path to your copy of the dp-api-clients-go directory.
Then …
=> Zebedee client can now be more configurable

dataset/dataset.go, dataset/dataset_test.go, filter/filter_test.go
We identified a bug in develop, where some dimension options failed to be added to filters. After some investigation, we found that the issue was with URL encoding of IDs passed as query parameters when we were validating them.
This PR fixes this bug by escaping all the IDs as part of the query param validation.
- Make sure unit tests pass and cover the new functionality
Anyone
=> As part of the query parameter validation, the provided IDs are escaped.

LICENSE.md, README.md, image/data.go
Add an error field to the image model (similar to the one in the ImageDownload model). This means that when the image import/publish fail, a descriptive reason can be supplied as well. This requires a correlating change in `dp-image-api` (https://github.com/ONSdigital/dp-image-api/pull/47) 
Ensure the new field has been added.
Anyone but me.
=> Add error field to image api model

dataset/dataset.go, dataset/dataset_test.go
Undid the query parameter escaping because some services need it but not others.
Make sure only the encoding and test have been removed
anyone
=> Undid the query paramter escaping, as this needs to be service specific.

image/image.go, image/image_test.go
Image client was expecting a 200 (OK) on publish but the API returns no content so this should be 204 (NoContent).
There is a corresponding PR on the image API https://github.com/ONSdigital/dp-image-api/pull/48
Ensure code as expected and tests etc. pass.
Anyone but me.
=> Expect 204 on image publish

dataset/data.go, dataset/dataset.go, zebedee/client.go, zebedee/data.go
- Fix Zebedee add to collection methods. Was marshalling state as a string rather than an object
- Add new update instance model. PUTting an instance doesn't allow some fields, so a custom update model has been added so as not to break backwards compatibility. A task has been added to look at consolidating models where possible
Anyone
=> Fix zebedee add to collection methods and add new update instance model

dataset/dataset.go, dataset/dataset_test.go, filter/filter.go, filter/filter_test.go
After the changes in filter and dataset APIs to comply with the latest pagination standards, we no longer can pass a value of limit=0 to obtain all values (default behaviour in the past). In this task, we allow the caller to decide if they want to pass query parmters or not, by making the parameter a pointer:
- nil pointer results in the request being sent with no query paramters.
- valid pointer results in the limit and offset being sent as query paramters.
Anyone
=> make query parmters optional (nil value) for filter api client

site-search/data.go, site-search/site-search.go, site-search/site-search_test.go
- Rename `search-query` client to `search-api` client
- Check if there are any references to `dp-search-query`
Anyone
=> rename search-query client to search-api client

dataset/data.go
Nomis Metadata for datasets are now loadable and presentable on the website (note the user is directed to Nomis for the dataset contents).
It should look something like this:
First things first you will need Nomis datasets locally
You will need to navigate in terminal to your local `dp-dataset-api` ensure you have the latest version on the develop branch. Then run `make Nomis` this command will populate your local MongoDB instance with new datasets. These are stored in a similar way to CMD datasets.
You will then need to pull the following locally:
- https://github.com/ONSdigital/dp-frontend-models/pull/86
- https://github.com/ONSdigital/dp-api-clients-go/pull/98
- https://github.com/ONSdigital/dp-frontend-dataset-controller/pull/204
- …
=> Nomis datasets added

dataset/data.go, dataset/dataset.go, dataset/dataset_test.go
Add pagination support for the `/datasets` endpoint
- Added parameter to the original `getDatasets` function, allowing pagination parameters to be passed in.
- Added a new function `GetDatasetsInBatches`, which gathers all the pages of datasets and returns the entire list. 
Review changes / tests
Anyone
=> Add pagination support for the `/datasets` endpoint

batch/batch.go, batch/batch_test.go, dataset/dataset.go, dataset/dataset_test.go
Bugfix: Get Instance Dimensions was not passing the query paramters to the request - this is currently affecting dimension-importer in develop.
- Fix the bug
- Added unit tests
- Added param validation for batch processing functions, to prevent any panic on invalid situations.
- (info only) I tested the changes by creating a real client, with a connection against my local dataset API.
Anyone
=> Fixed Get instance dimensions when providing query parameters

README.md
Previously being an absolute link - it would fail due to branch being deleted.
Now the absolute link will always work (unless the file is removed) on any branch. It will also prevent the user when clicking the link to jump to a different branch (which would happen if it were an absolute link).
Check health link works
Anyone
=> Update documentation link to health package to be relative link

dataset/data.go, dataset/dataset.go, dataset/dataset_test.go
- Implemented `PostInstance` method for dataset API client.
- Created unit tests
This is required by import API, which currently uses an implementation in the service itself and is being replaced with this one.
- Make sure new tests make sense
Anyone
=> implemented PostInstance, requried by import API

dataset/dataset.go
Added 'detached' state to list of state consts to keep in line with dp-dataset-api
Check changes won't break anything. Part of a 3 change across 3 services which need to be tested
together once merged to develop.
Anyone, prefer some input from someone experienced with code base to see if this is an appropriate change or not
=> Add detached state to list of available states

Makefile, ci/lint.yml, ci/scripts/lint.sh, zebedee/client.go, zebedee/client_test.go
Fixed an issue where an absolute url for a download file in data.json was still appended onto the page url: 
Check against existing content. If you are reviewing pls contact me for a URL with an absolute path
Anyone with sufficient knowledge of this repo
=> fix download files in datasets that have absolute url

codelist/codelist.go, codelist/codelist_test.go, filter/filter.go, headers/headers.go, headers/headers_test.go, identity/authentication.go, identity/authentication_test.go, recipe/client.go
As part of the new Authentication work, we will be replacing X-Florence-Token which is validated via Zebedee with a new token that uses the Authorization header instead which is validated by the dp-identity-api.
But wait we need a smooth transition! Yes, and so we have a new function for setting authentication header `SetAuthToken` this will set both the old Zebedee token and the Florence token. There is work in progress to make requests to the dp-identity-api that fail auth to then check Zebedee with the X-Florence-Token. This work is WIP.
You may notice that the serviceAuthToken also uses the header `Authorization`! Won't there be a collision? - Yes. The idea behind this work is to handle these collisions later, potentially what we will do is check the dp-identity-api to see if it is a …
=> Replacement for setUserAuthToken introduced

dataset/data.go
Added new Cantabular model fields to dataset client to match dp-dataset-api models
Make sure code makes sense, tests pass.
Can check relative values in dp-dataset-api/models/ (type Instance and type Dimension) to see they match in type and JSON tags
Anyone
=> add type, isBasedOn, variable and numberOfOptions

Makefile, importapi/importapi.go, importapi/importapi_test.go
Added a new func for the new endpoint in import api :
- endpoint: `PUT /jobs/{id}/processed/{instanceID}`
- method: `IncreaseProcessedInstanceCount`
Added unit tests
Make sure code changes make sense and tests pass
(note) I tested it by using it in `dp-import-cantabular-dimension-options`
anyone
=> Add IncreaseProcessedInstanceCount call in import api, with unit tests

clientlog/clientlog.go, clientlog/clientlog_test.go, codelist/codelist.go, dataset/dataset.go, filter/filter.go, go.mod, go.sum, health/health.go, hierarchy/hierarchy.go, identity/authentication.go, identity/authentication_test.go, image/image.go, importapi/importapi.go, recipe/recipe_test.go, renderer/renderer.go, site-search/site-search.go, zebedee/client_test.go
Update log.go requirement to v2 in go.mod and imports.
Update logging statements to format that can be parsed by
elastisearch, e.g.
log.Event(ctx, string, log.FATAL, log.Error(something1), something2)
-> log.Fatal(ctx, string, something1, something2)
log.Event(ctx, string, log.ERROR log.Error(something1), something2)
-> log.Error(ctx, string, something1, something2)
log.Event(ctx, string, log.INFO, log.Error(something))
-> log.Info(ctx, string, log.FormatErrors([]error{something}))
log.Event(ctx, string, log.WARN, log.Error(something))
-> log.Warn(ctx, string, log.FormatErrors([]error{something}))
These changes needed to allow error logs to be properly viewed in
kibana.
run make test
eyeball changes for obvious errors
Anyone
=> update log.go to v2, update logging statements for elastisearch

dataset/data.go
Improved the Downloads model in UpdateInstance (according to models defined in dp-dataset-api)
- Make sure code changes make sense. You may check the dataset api models [here](https://github.com/ONSdigital/dp-dataset-api/blob/develop/models/instance.go#L17)
anyone
=> Add method to put download info to instances (dataset api)

dataset/dataset.go, dataset/dataset_test.go
- Created `PatchInstanceDimensions` method to call `PATCH /instances/{id}/dimensions` endpoint
- Unit tested
- Make sure code chnges make sense
(info) - I tested the changes by implementing a unit test that does a real connection, against a dataset api instance running locally (using https://github.com/ONSdigital/dp-dataset-api/pull/313):
```
func TestReal(t *testing.T) {
Convey("asdf", t, func() {
cli := NewAPIClient("http://localhost:22000")
serTok := "<your local service auth token>"
instID := "<existing instance ID in your mongoDB>"
data := []*OptionPost{
{
CodeList: "codeList",
Option:   "ooop1",
},
{
CodeList: "codeList",
Option:   "ooop2",
},
}
_, err := cli.PatchInstanceDimensions(ctx, serTok, instID, data, "*")
So(err, ShouldBeNil)
})
}
```
anyone
=> implemented PatchInstanceDimensions

cantabular/table.go, cantabular/table_test.go
Have ported the response parsing logic and tests from dp-cantabular-csv-exporter so it can be reused in dp-observation-api (and anywhere else that needs it in the future)
Check tests pass and code makes sense, only expected code is present.
Anyone
=> integrate table parsing logic for Cantabular client

cantabular/static_dataset.go, cantabular/static_dataset_test.go
Added parsing for GraphQL errors returned from Cantabular. GraphQL errors don't come back as actual
errors or with an error code, rather you have to check whether the error field in the response has been populated. 
With this change the Cantabular Client will now convert this into an error with the appropriate status code.
Check code changes make sense, tests pass.
To test locally you can cause a GraphQL error by modifying the recipe to have too many variables or editing the code to pass incorrect variables.
Anyone
=> add parsing for graphql error

dataset/data.go
This has been done because:
1. It should not be in that struct
2. Its in the Version struct
3. recent code updates caused clashes in un-marshalling that showed the issue.
Visual inspection
Anyone.
=> Remove UsageNotes from DatasetDetails struct

dataset/data.go, dataset/dataset.go, dataset/dataset_test.go
Modified `PatchInstanceDimensions` func to provide updates for multiple existing options (using the latest changes of dataset api)
Trello card https://trello.com/c/fkwR6fiM/5253-cmd-import-use-single-patch-call-per-batch-of-dimension-options
anyone
=> Add optionUpdates to PatchInstanceDimensions

cantabular/dimension.go, cantabular/static_dataset.go, cantabular/static_dataset_test.go, cantabular/table.go, stream/stream.go, stream/stream_test.go
- Renamed r/w to pipeReader/pipeWriter to improve code readability
- Transformer func calls `CloseWithError` if the transform func returned an error (and `Close` otherwise)
- Fixed tests accordingly: we no longer see the `EOF` error, and any error in the transformer is passed to the consmer.
- Pass the context provided to `StaticDatasetQueryStreamCSV` down to the json streamer iterator, and abort processing if the context is cancelled 
Use XLSX exporter as a reference.
Anyone
=> improved Stream error handling, closing and var names

recipe/client.go
Recipe API client now ignores ErrValueEmpty, which is a valid scenario for values that are not supposed to be set (e.g. maybe we want to set service token but not user token)
- (info) validated with [`dp-import-cantabular-dataset` PR ](https://github.com/ONSdigital/dp-import-cantabular-dataset/pull/32)
anyone
=> Recipe API client must ignore ErrValueEmpty

dataset/data.go
Add struct to enable cantabular xlsx exporter to get dataset version links (due to clash with metadata struct also having json name of 'links')
Related to this PR - https://github.com/ONSdigital/dp-dataset-api/pull/344
Confirm changes are correct and make sense
Anyone
=> add dataset links struct

zebedee/client.go, zebedee/client_test.go, zebedee/data.go, zebedee/response_mocks/publishedindex.json
Added PublishedIndex endpoint to zebedee client
- Includes paging parameters (although zebedee currently ignores these)
- Corresponding zebedee PR: https://github.com/ONSdigital/zebedee/pull/551
Check code and unit tests
Anyone but me
=> Add published index endpoint for search reindexing

cantabular/client.go, cantabular/codebook.go, codelist/codelist.go, headers/headers.go, headers/headers_test.go, recipe/client.go
Bugfix: 
When the headers error handling was fixed, it caused that errors setting headers were being returned to the caller.
Most callers assumed that empty values would be allowed, so that fix broke some expectations of callers, because by default, all headers would expect non-empty values, and fail with `ErrValueEmpty` otherwise.
In this PR we ignore `ErrValueEmpty` when trying to set any header, but the error type has been kept and returned by the lower level func `setRequestHeader` so that if a header becomes mandatory, we can just forward this error to the caller in the future.
anyone
=> do not error on empty values when setting headers (for all headers)

cantabular/contract.go, cantabular/gql/data.go, cantabular/gql/error.go, cantabular/queries.go, cantabular/static_dataset.go, cantabular/static_dataset_test.go
- Implemented GetDimensions for Cantabular using graphQL (query all variables for a provided dataset)
- Implemented GetDimensionsByName for Cantabular using graphQL (query only provided variables for a dataset)
- Implemented GetDimensionOptions for Cantabular using graphQL (query categories for provided variables and dataset)
- Added unit tests
trello card: https://trello.com/c/P1WrnEct/5439-add-method-to-dp-api-clients-go-for-cantabular-flexible-datasets
used by:
- https://github.com/ONSdigital/dp-import-cantabular-dataset/pull/37
- https://github.com/ONSdigital/dp-import-cantabular-dimension-options/pull/36
- (tried locally, no need to reproduce) You can run Cantabular server and API ext locally, and replace the unit test …
=> Implement Cantabular GetDimensions and GetDimensionOptions with graphql

cantabular/client.go, cantabular/dimensions.go, cantabular/gql/error.go, cantabular/gql/error_test.go, cantabular/queries.go, cantabular/static_dataset.go, cantabular/static_dataset_dimension.go, cantabular/static_dataset_test.go, cantabular/table.go
Modified StatusCode in returned Cantabular error to pass the error code defined in the Cantabular error message (instead of propagating the status code 200 OK, which is returned by cantabular itself)
Needed in order to return the right status in the cantabular dimensions api:
[Trello card](https://trello.com/c/tSdkHCF2/5452-get-area-types-implement-endpoint-8)
anyone
=> extract cantabular status code from error message

interactives/data.go
Add import message - mainly for reporting error message back when failure.
=> Add ImportMessage attribute to interactives client

filter/data.go, filter/filter.go, filter/filter_test.go
Added CreateFlexibleBlueprint function to accept population type field
Refactored code to share implementation between CreateFlexibleBlueprint and CreateBlueprint
Corrected tests for CreateBlueprint
Added tests for CreateFlexibleBlueprint
Refactoring is sound
New functionality is present
Tests cover functionality
gophers other than @goofballLogic
=> Add CreateFlexibleBlueprint method to dp-api-clients-go

filter/data.go, filter/filter_test.go
We were missing a few fields on returned Dimensions, this adds them in.
Confirm the API changes match the schema as defined in the [pagination PR](https://github.com/ONSdigital/dp-cantabular-filter-flex-api/pull/21).
Anyone.
=> Add missing fields to Filter Dimensions (Ticket #5559) 

dataset/data.go, dataset/dataset.go
This PR creates the edition details object with current and next edition details. Also this implements the full edition details api maintaining backwards compatibility with ```GetEditions``` which actually returns the next editions only. 
This is already used and tested by the indexing script of the dp-search-api
Anyone except me (but @nshumoogum  will be preferred because of the familiarity with the context)
=> Add full edition details api

filter/data.go, filter/filter.go, filter/filter_test.go
Adds a new client method to the `filter` API client which conforms to the new endpoint as implemented [here](https://github.com/ONSdigital/dp-cantabular-filter-flex-api/pull/25).
We can't simply add new fields to the existing `AddDimension` method since:
- It would be a breaking change to the signature.
- CMD requests don't need the additional fields, so it would nonsensical to have to pass placeholder/empty values.
- The new endpoint doesn't have the `/{name}` suffix, instead including the name only in the request body.
- Passing additional fields in the body may break CMD consumers (e.g. if they are using `Decoder.DisallowUnknownFields`).
Ticket: https://trello.com/c/MuClZX8t
Confirm the client meets the spec of the new [endpoint](https://github.com/ONSdigital/dp-cantabular-filter-flex-a …
=> Create AddFlexDimension method on Flex client (Ticket #5602)

dimension/area_types.go, dimension/client.go, dimension/client_test.go, dimension/error.go
Adds a new API client for the Dimension API. Only includes one method currently, `GetAreaTypes`, which is required for [5569](https://trello.com/c/yOjZDYAj).
Check the client matches the schema [defined by the API](https://github.com/ONSdigital/dp-cantabular-dimension-api/blob/e28c30655025a372204796efef9b5acdcdf00be8/swagger.yaml#L10).
Anyone.
=> Add Dimensions API client

areas/data.go
The geometry field sent from areas api should probably be sending a [][][]float32 but its actually been sent as a string.
just check that the geometry field is now type string
anyone
myself
=> Should be [][][]float32 but sent as a string

dimension/area_types.go, dimension/client_test.go
Returns the newly exposed `total_count` property from [https://github.com/ONSdigital/dp-cantabular-dimension-api/pull/9](https://github.com/ONSdigital/dp-cantabular-dimension-api/pull/9) as `TotalCount` on the dimension client.
This is to enable the area selection radio buttons to display the count in the label.
https://trello.com/c/yOjZDYAj/5569-create-front-end-to-display-list-of-area-types
Check the code.
Anyone.
=> Return TotalCount from area-types endpoint

areas/areas.go, areas/areas_test.go, areas/data.go
Remove Ancestor struct & GetAncestors
We don't have a requirement for a GetAncestors func anymore as this data is returned in the `/areas` response under the `ancestors` key.
We also don't require the Ancestors struct as we can use `[]Ancestor` instead without the double nested `Ancestor.Ancestor` struct member access notation. 
Run the tests
Run: `make test`
anyone
myself
=> Removes getAncestor

interactives/interactives.go, interactives/interactives_test.go
Version interactives client endpoints
Healthcheck is not versioned so we either need 2 clients or add a v1/health.
=> Add version to interactives client

upload/client.go, upload/client_test.go
Upload client currently only reads partial content when reader is for a file within a zip archive.
Check test scenario covers issue.
Another
=> Use io.ReadFull to read full content for zip file

filter/contract.go, filter/filter.go, filter/filter_test.go
Added `GetFilter` client function.
This deprecates GetJobState as the models/contract used no longer resemble the behaviour of dp-filter-api.
Check code makes sense, tests pass
Anyone
=> Add new client function for filter-api GET /filters

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/gql/data.go, cantabular/queries.go
Adds a new method which allows for the search/retrieval of areas for a specific area type (e.g. all the areas for `City`).
Resolves [#5651](https://trello.com/c/PDCxskCW)
Confirm the method follows the format/structure of the existing API methods and unit tests.
Anyone.
=> Add GetAreaTypeAreas method to Cantabular client (#5651)

filter/data.go, filter/filter_test.go
Adds the ID/Label fields to returned filter dimensions. The client component of [this PR](https://github.com/ONSdigital/dp-cantabular-filter-flex-api/pull/60).
Required as part of the census pages and the select area-type journey. 
Resolves: [5664](https://trello.com/c/3TbBPTvY)
Sense check.
Anyone.
=> Add ID/Label to filter dimensions (#5664)

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/gql/data.go, cantabular/queries.go
Added pagination to GetGeographyDimensions function, to be used by GET /area-types in dp-cantabular-dimension-api
Enables passing of limit and offset and responds with limit, offset, count and total count
Related to https://github.com/ONSdigital/dp-cantabular-dimension-api/pull/13
Check changes make sense and tests pass
Anyone
=> add pagination to GetGeographyDimensions

dimension/areas.go, dimension/client.go, dimension/client_test.go
Adds `GetAreas` to the dimension client. Also deduplicated some code around creating the dimension requests.
Context:
[https://trello.com/c/HNH1I1Dj/5650-add-getareas-method-to-cantabular-dimensions-api-client](https://trello.com/c/HNH1I1Dj/5650-add-getareas-method-to-cantabular-dimensions-api-client)
Check code and tests against ticket/
Anyone.
=> Add GetAreas to dimension client

download/download.go, download/download_test.go
Add dp-download-service client:
- follow pattern of other clients (lift n shift'ish 🤠)
- only one endpoint covered - as expected for this piece of work: https://github.com/ONSdigital/dp-download-service/blob/500edf0ca0b286f8542f4f7b831bd9168749ff86/swagger.yml#L72
- have tested locally
Sanity check and check test scenarios.
Anyone
=> Add dp-download-service client

dataset/contract.go, dataset/dataset.go, dataset/dataset_test.go
Added GetVersionMetadataSelection function to dp-dataset-api client.
This acts as the same as GetVersionMetadata except allows the caller to specify the list of dimensions returned in the metadata.
Check changes make sense, tests pass
Anyone
=> Add GetVersionMetadataSelection

filter/data.go, filter/filter.go, filter/filter_test.go
The **dp-cantabular-filter-flex-api** `/filter/{id}/submit` [endpoint](https://github.com/ONSdigital/dp-cantabular-filter-flex-api/blob/develop/api/filters.go#L221) is returning a `202 Accepted` HTTP response code.
Ensure tests run and check the **dp-cantabular-filter-flex-api** project.
Any developer
=> Expect HTTP Accepted code from  filters/{id}/submit

dataset/dataset.go, dataset/dataset_test.go
Work in reference to https://trello.com/c/o7gox9jw/5701-add-check-to-area-types-endpoint-to-ensure-population-type-is-published-for-public-users 
as now the client must be updated to use the new parameter in the `dp-population-types-api`
The is_based_on parameter is now part of the dataset-api
Added parameter to dataset function
run unit tests 
Anyone from Team-b
=> feat: is_based_on parameter added to GET list_datasets

population/area_types.go, population/areas.go, population/client.go, population/client_test.go, population/error.go
We need to create a new endpoint in dp-population-types-api with a route
`/population-types/{population-type}/area-types` and move the handler
code from dp-cantabular-dimensions-api in to the handler for this
route in the population-types-api.
This change adds a new population-types API client.
This will be required for the FE work.
Resolves: 5672
Depends on:
* https://github.com/ONSdigital/dp-population-types-api/pull/12 _(Merged)_
* https://github.com/ONSdigital/dp-cantabular-dimension-api/pull/14
Ensure tests pass and check the logic.
Any developer
=> 5672 Create Population Types API client to query Area types

ci/lint.yml, filter/data.go, filter/filter_test.go, go.mod
the whole v2 lib was importing v1 of itself for the `filter` client
when it seemingly need not do so
so, tidied that up
does it still work
!me
=> remove filter v2 dependency on filter v1; make go version consistent

filter/filter.go, filter/filter_test.go
`DeleteDimensionOptions` completely removes the options array from a
given dimension and filterID
Resolves: [5732 - dp-api-clients-go function for DELETE filters/{filterid}/dimensions/{dimension}/options](https://trello.com/c/XBSVWDXW/5732-dp-api-clients-go-function-for-delete-filter-filterid-dimension-dimension-options)
Sense check it.
Any ONS developer.
=> 5732 - Add delete dimension options function

interactives/data.go, interactives/interactives.go, interactives/interactives_test.go
- main motivation was to refactor the InteractiveArchive.ArchiveFiles attribute - this is nonsense with a huge zip file of 000s k files
- added `UploadRootDirectory` - this will be used to render the file via dp-frontend-interactives-controller
- some housekeeping - renamed dropping `Interactives` as already namespaced by package
Tested locally - when merged I can create other PRs with this version bumped
Sanity check
Anyone
=> Refactor handling archive files for interactives

interactives/data.go
Dropping the redundant `PatchArchiveFile` operation. No longer required as not persisting all the files within zip at our end - we already store relevant files for ui in `html_files`.
👀 
Anyone
=> Remove patch file operation from interactives client

cantabular/dimensions_test.go, cantabular/gql/data.go, cantabular/queries.go
In Cantabular version 10.1 the FilterOnly field has been changed to be a boolean value from a string type so is causing issues when running imports locally.
We do not need to use this in our queries so it can be removed completely
Trello - https://trello.com/c/YkgpIV1l/5778-remove-filteronly-from-cantabular-queries
Confirm changes match Trello ticket request
Anyone
=> #5778 - remove FilterOnly field

cantabular/queries.go
When we send a query to `dp-cantabular-api-ext` to retrieve a list of
categories for a variable, we are also requesting the values
(i.e. the observation numbers) which is not needed here.
It was triggering the SDC rules applied on the population-type.
Subsequent PRs will have to be raised.
Resolves: [5785](https://trello.com/c/BgynyRgB/5785-update-cantabular-query-that-retrieves-dimension-options)
Sense check it and ensure tests are :green_circle: 
=> 5785 - Do not request 'values' when querying Dimension Options

dataset/data.go, dataset/metadata_test.go
As currently structured the Metadata struct has both an embedded Version and DatasetDetails object. Each of these has a Links ('json: links') attribute, and the default json marshaller fails to populate either field. In order not to introduce a breaking change to the api, a bespoke json Unmarshaller is used to do the disambiguation
Review code and ensure all tests are passing
Anyone
=> Add json unmarshaller for the Metadata struct

dataset/data.go
As currently structured there is a mismatch between the dp-clients DatasetDetails and the dp-dataset-api DatasetDetails in that one has the NationalStatistic bool attribute as a straight bool and one has a *bool. Both use the json 'omitempty' tag. This means that a client using the dp-clients DatasetDetails will never send the NationalStatistic field in its JSON rendering when the field has a value of false, and consequently the receiving dp-dataset-api DatasetDetails will always have its value set to nil. In at least one situation (PutDataset()), this means the value of NationalStatistic can never be set to false. Changing the dp-clients DatasetDetails to have a *bool would be a breaking change, so removing the 'omitempty' flag is the solution chosen, as this is not strictly a breaking …
=> Remove the 'omitempty' json tag on the NationalStatistic attribute in dataset.DatasetDetails

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Add new GetAggregatedDimensionOptions, an alternative to GetDimensionOptions specifically for importing static datasets for aggregated population types.
Anyone
=> Add GetAggregatedDimensionOptions func

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Previously the endpoint
```
GET /population-types/{dataset}/area-types/{area-type}/areas/{area-id}
```
was performing a fuzzy search and limiting the results to 1.
Since cantabular api extension  v10.2.1 we can now match exactly an area id.
This is the change to perform an exact match.
Resolves: [5849](https://trello.com/c/epE8FvNN/5849-getarea-endpoint-returning-error-results)
Sense check it and ensure tests are :green_circle: 
ONS developers
=> 5849 Create a 'GetArea' function to perform an exact match

population/area_types.go, population/areas.go, population/client_test.go
@mr-nick17 has raised this as an issue, after updating the `dp-population-types-api` REST endpoints I forgot to update the response models of the it's go api client.
Resolves: [5851](https://trello.com/c/7yZXgUEJ/5851-bug-fix-count-on-review-page-update-api-clients-go)
Sense check it and ensure tests are :green_circle: 
Any ONS developer.
=> 5851 Update client's models to include the PaginationResponse

cantabular/dimensions.go, cantabular/dimensions_test.go
Ammended categorisations method not to use variable but to use text as defined in the query. Previously It was using an empty string, resulting in the same response for every dimension in the cantabular dataset.
TeamB
=> fix: get categorisations

population/client.go, population/client_test.go
A new GET endpoint is needed to retrieve the count of areas within the larger area-type.
URI would be
```
/population-types/{population-type}/area-type/{area-type}/parents/{parent-area-type}/areas-count?areas=put,your,list,of,areas,here.
```
This should just return an integer of the count of the number of areas within the original area type within the larger area.
Resolves: [5858](https://trello.com/c/oDyIu8hU/5858-create-endpoint-to-get-the-count-of-areas-within-the-larger-area-type)
Depends on:  https://github.com/ONSdigital/dp-population-types-api/pull/75
* Sense check it
* Ensure tests are :green_circle:
=> 5858 Create 'GET' parent areas count function

population/client.go, population/client_test.go
* The value returned by the Populations API is an `int` and not a `string`.
* Amend the parent areas count query param structure  
It should be `?areas=area1,area2`
And not `?areas=area1&areas=area2`
**Resolves**: [5843](https://trello.com/c/cKGTgs1o/5843-fix-count-on-pages-that-getareas) [5858](https://trello.com/c/oDyIu8hU/5858-create-endpoint-to-get-the-count-of-areas-within-the-larger-area-type)
* Sense check it
* Ensure test are :green_circle: 
* Check with @mr-nick17 
=> 5858 - Amend the parent areas count type

cantabular/client.go, cantabular/client_test.go
Currently when our services do a healthcheck against `cantabular-api-ext` an empty query is sent to check the connectivity which is throwing errors in the logs and making it difficult to debug the extended api.
The error that appears on the logs is the following:
```
t=2022-09-21T16:27:56Z ns=api-ext lvl=info ev=graphql query={} op= vars=
t=2022-09-21T16:27:56Z ns=api-ext lvl=info ev=message msg="GraphQL error: Syntax Error GraphQL request (1:1) Unexpected empty IN {}\n\n1: {}\n   ^\n"
t=2022-09-21T16:27:56Z ns=api-ext lvl=info ev=http port=8492 url="/graphql?query={}" method=GET httpStatus=200 contentType=application/json remoteAddr=172.20.0.34 authUser= nBytes=150
```
Going forward the response on the logs should be:
```
t=2022-09-21T17:06:33Z ns=api-ext lvl=info ev=graphql …
```
=> 5862 Update Cantabular API Ext healthcheck GraphQL query

population/area_types.go, population/areas.go
Change the return keys of the structs in population types area methods to reflect ONS standard 
Check that unit tests work  
team b
=> fix: use "items" key instead of struct type

dataset/data.go, dataset/data_test.go
Since the `SubTopics` field of the `DatasetDetails` model is an optional field, the user should be able to remove the sub-topics selection once saved to the dataset model. This functionality was lost due to various changes made to the `dp-dataset-api` while fixing another [bug](https://github.com/ONSdigital/dp-dataset-api/pull/379). Wrapping the `SubTopics` update statement in a guard, in the `dp-dataset-api`, is not allowing the user to delete an existing `SubTopics` selection because when an empty slice is passed down from the [dp-publishing-dataset-controller](https://github.com/ONSdigital/dp-publishing-dataset-controller) service to `dp-api-clients-go` library due to the `omitempty` tag in the `dp-api-clients-go` the `SubTopics` key is omitted from the JSON object sent to the …
=> Update Subtopics property of the dataset model to be a pointer

dataset/data.go, dataset/data_test.go
Adds support for related content field in dataset model, for use in Cantabular metadata journey.
Read the code and run the tests.
Anyone
=> adds related content field to DatasetDetails response dataset model

cantabular/metadata.go
"failed to make GraphQL query: slice doesn't exist in any of 1 places to unmarshal" error seen with extractor-api running against v1.3 metadata as deployed. Questions is now an array according to SCC so we need a []struct.
Quick test: run a local "dp-cantabular-metadata-extractor-api" server via make debug but point at a metadata server port forwarded from sandbox.  Also modify the extractor-api to use this version of "dp-api-clients-go"
curl -v  http://localhost:28300/cantabular-metadata/dataset/TS009/lang/en
should return a JSON response rather than an error
Rafa
=> questions is now a JS array

zebedee/client.go, zebedee/client_test.go
Do not ask Zebedee for data set descriptions for the new CMD or Cantabular datasets (it doesn't have their descriptions)
Review changes and ensure tests are passing
Anyone
=> Fix - remove call to Zebedee for data set descriptions for the new CMD or Cantabular datasets

cantabular/client.go, cantabular/client_test.go
Add health checker function for `dp-cantabular-metadata-service`
Note there is no health endpoint in there so we are making a call to the `graphql` endpoint.
Also note that we use the ext-api host as that is how it is configured to be used despite it actually using the metadata service URL. This needs to be revisited and refactored.
Anyone
=> Add checker for metadata service

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
If a total count is included in the response for a Cantabular query, it always return the count of super-set and not the subset based on search criteria.This change is to return the total count based on the result of search criteria 
Anyone
=> Fix for total count

population/areas.go, population/client_test.go
Add SVarID (supplementary variable) to population/GetParentAreaCount
Allows additional variable to be sent to the parentAreaCount query for pre-built tables.
Anyone
=> population - add svar to GetParentAreaCount

cantabularmetadata/classification.go, cantabularmetadata/classification_test.go, cantabularmetadata/contract.go
Amend default categorisation method to handle less failure cases (and send responsibility of that to the server)
change response to return list instead of string as main struct variable
Amend tests to reflect lesser error handling
=> feat: default categorisation change

go.mod, population/population_types.go
Restore git history of deleted v2.226.0 and v2.227.0 releases. Also add retraction notice to the go.mod so they aren't used.
Ensure tests pass, history looks good and `retract` block looks correct.
Anyone but me
=> Release v2.32.1 - retract bad versions

cantabular/metadata.go
`failed to make GraphQL query: struct field for "E06000001" doesn't exist in any of 1 places to unmarshal` error seen with `extractor-api` running against the latest version of metadata in sandbox at the time of writing. `CatLabels` was originally declared of type string and it was returned as `null` by the previous metadata versions, but it seems that in the most recent version it is an object, hence the error. As a fix, instead of updating the field type, it was agreed to remove the `catLabels` field from the extractor response since it isn't referenced anywhere in the cantabular journey. (ticket#1436)
Quick test: run a local "dp-cantabular-metadata-extractor-api" server via make debug but point at a metadata server port forwarded from sandbox. Also modify the `extractor-api` to use …
=> Removes catLabels field from extractor response

cantabular/queries.go, cantabular/static_dataset.go, cantabular/static_dataset_test.go
ticket; https://trello.com/c/09GkfSkR/6071-ensure-census-observations-in-population-types-api-works-for-microdata-types-only
Added support for new query to get type of dataset. This could have been achieved by adding the type to existing 'QueryStaticDataset' but running that query is expensive. So added a query that will quickly determine the 'type' 
Anyone
=> Added support for new query to get type of dataset

dataset/data.go, dataset/dataset.go, dataset/dataset_test.go
- Add new function returning headers for Get version. Currently only containing etag
- Add unit test for the happy path of GetVersion and for the new function GetVersionWithHeaders
- Refactor checks of the response headers in unit test so to expand it to collection id, florence token and download service token.
Check the code and test look ok
See https://github.com/ONSdigital/dp-dataset-api/pull/416 for the change in dataset api introducing the etag in the header
Anyone.
=> New function to read version etag 

cantabular/static_dataset.go
Amended function name to have an uppercase JSON as currently dp-cantabular-filter-flex-api fails the lint step due to this naming convention.
Anyone.
=> Fix function name to pass lint step

cantabular/table.go
Adding version and metadata links to cantabular responses following updates to dp-cantabular-filter-flex to stop OOM kills.
This is a non-breaking change - have tested with the other service that uses this data model.
Anyone.
=> Adding additonal links section
