zebedee/client.go, zebedee/client_test.go
Initialise new client rather than get passed one
Anyone
=> Initialise new client rather than get passed one

codelist/codelist.go, codelist/codelist_test.go
Updated codelist client to include `userAuthToken` parameter for all methods and updated tests.
=> added user auth token parameter to all client methods

headers/headers.go, headers/headers_test.go
Added functions to headers package to get/set the user auth token header plus unit tests.
=> added get/set functions for user auth token header plus unit tests

headers/headers.go, headers/headers_test.go
Added get/set function for service auth token plus unit tests.
=> added set/get functions for service auth token header plus unit tests

filter/filter.go, filter/filter_test.go
* userAuthToken added to filter api client
* renamed testing vars to be inline with other client tests
* added nil body close check
Anyone except me
=> Enable filter client to accept user auth token

headers/headers.go, headers/headers_test.go
Added get/set functions for locale code header. Added unit tests for new functions.
=> added get/set functions for locale code header + unit tests

identity/authentication.go, identity/authentication_test.go
Updated identity client to migrate from old `common` headers to new `headers` package. And updated tests
Code review, run locally, run tests.
Anyone else.
=> updated identity client to migrate from common -> headers

zebedee/client.go, zebedee/client_test.go
Fix query param encoding.
Anyone but me.
=> Fix query param encoding

zebedee/client.go, zebedee/client_test.go
- Created GetWithHeaders function. This is required by dp-frontend-router middleware, and will probably be needed by other apps in the future.
Check that the unit tests pass and changes make sense
Anyone.
=> Add GetWithHeaders, and covered header extraction in existing 'get' test

baseclient.go, codelist/codelist.go, codelist/codelist_test.go, dataset/dataset.go, dataset/dataset_test.go, filter/filter.go, filter/filter_test.go, go.mod, go.sum, health/health.go, health/health_test.go, hierarchy/hierarchy.go, hierarchy/hierarchy_test.go, importapi/importapi.go, importapi/importapi_test.go, renderer/renderer.go, renderer/renderer_test.go, search/search.go, search/search_test.go, zebedee/client.go, zebedee/client_test.go
Abide by latest dp-healthcheck library definition of checker function
Check changes make logical sense
Check unit tests still pass
Anyone
=> Update checker functions

zebedee/client.go, zebedee/client_test.go
See title
Check tests still pass
Anyone
=> Rename client package to zebedee

dataset/data.go, dataset/data_test.go
See title
* Make sure code changes make sense
* Unit test pass
Anyone
=> Handle nil pointers when converting data to a string

dataset/dataset.go
Use the tokens passed in function by signature instead of retrieving from context
Check changes make sense and unit tests pass
Anyone
=> Stop using common package to retrieve tokens from context

zebedee/client.go, zebedee/data.go
Move Zebedee data model from `go-ns` 
Anyone
=> Move Zebedee data model

go.mod, go.sum, zebedee/client.go, zebedee/data.go
Add timeseries method to Zebedee client
Anyone
=> Add timeseries data to Zebedee client

image/data.go, image/image.go, image/image_test.go, image/response_mocks/image.json, image/response_mocks/images_0.json, image/response_mocks/images_1.json
Added image-api client
Ensure that endpoints defined in [dp-image-api/swagger.yaml](https://github.com/ONSdigital/dp-image-api/blob/develop/swagger.yaml) have been implemented and tested.
Anyone but me
=> Add image-api client

image/image.go, image/image_test.go
For Image API client:
- Added headers for service auth, user auth and collectionID
- Modified unit tests to verify headers for all calls 
Anyone
=> Added auth toknes to image api

image/data.go, image/image.go, image/image_test.go
- Created Publish function for ImageAPI client
- Unit tests 
Anyone
=> Image API client 'publish' endpoint

image/image.go, image/image_test.go
ImageAPI Client CompleteDownloadVariant implemented and tested
Anyone
=> Image API CompleteDownloadVariant

image/image.go, image/image_test.go, image/response_mocks/download.json
- Implement and test PutDownloadVariant
Anyone
=> Implement put image download variant endpoint

zebedee/data.go
Map release date to time series client response
Anyone
=> Map release date to time series client response

filter/filter.go, filter/filter_test.go
Filter client with constructor passing existing heath check client
- extract functions in filter_test.go
- make variable naming more consistent in filter_test.go
Review changes + check tests
Anyone
=> Filter client with constructor passing existing heath check client

dataset/dataset.go, dataset/dataset_test.go, renderer/renderer.go, renderer/renderer_test.go
Dataset and renderer clients with constructor passing existing heath check client
Review changes / check tests pass
Anyone
=> Dataset and renderer clients with constructor passing existing heath check client

hierarchy/hierarchy.go, hierarchy/hierarchy_test.go, zebedee/client.go, zebedee/client_test.go
Zebedee and hierarchy clients with constructor passing existing heath check client 
Review changes / check tests
Anyone
=> Zebedee and hierarchy clients with constructor passing existing heath check client 

search/search.go, search/search_test.go
Created Search API constructor that accepts a health client, and reuses its clienter.
- Unit tests should pass
Anyone
=> Created Search API constructor which accepts a healthcheck client

zebedee/client.go, zebedee/client_test.go
Stop using values in context instead use args passed to client
Anyone
=> Stop using values in context instead use args passed to client

zebedee/client.go
Add get resource body method
Anyone
=> Add get resource body method

zebedee/client.go, zebedee/data.go
Add GetCollection method to Zebedee client
Anyone
=> Add GetCollection method to Zebedee client

zebedee/client.go
Fix get collection request URL
Anyone
=> Fix get collection request URL

dataset/dataset.go
Add method that returns dataset current and next docs
Anyone
=> Add method that returns dataset current and next docs

dataset/dataset.go, dataset/dataset_test.go
Remove duplicate unmarshal
Anyone
=> Remove duplicate unmarshal

site-search/site-search.go, site-search/site-search_test.go
- Update search client with constructor passing existing heath check client
- Update tests accordingly
- Check if the code changes make sense
- Check if the tests pass
Anyone
=> update search client passing healthcheck client

search/search.go, search/search_test.go
- Update references of `search` to `dimension-search` in `search` package
- Check if references of `search` in the search package have been renamed to `dimension-search`
- Check if the test passes
Anyone
=> update references of search to dimension-search

site-search/data.go
- Change all struct to be exported so that they can all be used in the `dp-frontend-search-controller`
- Check if all have been exported
- Check if the unit test passes
Anyone
=> export structs to allow use in search controller

Makefile, ci/audit.yml, ci/build.yml, ci/scripts/audit.sh, ci/scripts/build.sh, ci/scripts/unit.sh, ci/unit.yml
Part of a selection of PR to add CI folder for Library, that is <repo>/ci 
Add a PR for the repo and Concourse will go through build, test, and audit for this repo.
Anyone with Concourse knowledge.
=> Library CI files for dp-api-clients-go

Makefile, ci/audit.yml, ci/build.yml, ci/scripts/audit.sh, ci/scripts/build.sh, ci/scripts/unit.sh, ci/unit.yml, dataset/data.go, dataset/dataset.go, dataset/dataset_test.go
Add method for getting batches of versions
Anyone
=> Add method for getting batches of versions

dataset/data.go, dataset/dataset.go, dataset/dataset_test.go
Add batch processing for GetInstances and GetInstanceDimensions
Confirm changes are correct
Anyone
=> Add batch processing

site-search/data.go, site-search/response_mocks/departments.json, site-search/site-search.go, site-search/site-search_test.go
- Add get departments func to site-search client
Anyone
=> Add get departments func to site-search client

cantabular/client.go, cantabular/codebook.go
Added some addition logData to errors in Cantabular API as I found it useful in debugging.
Check makes sense, unit tests pass
anyone
=> Add url to logData in several places

dataset/dataset.go
Add comment to clarify that only one token needs a value (after confirming with Nathan).
Read changes.
Anyone
=> Add clarifying comment.

.travis.yml
Remove no longer used file.
Check only ".travis.yml" was removed.
Anyone
=> Remove travis.yml (no longer used)

renderer/renderer.go
- export `hcCli` to be used in `dp-frontend-search-controller` to mock the `Renderer` struct to allow component testing on `/health` endpoint
- Check if the code changes make sense
Anyone
=> export hcCli in renderer

site-search/data.go
Add additional suggestions to model
Anyone
=> Add additional suggestions to model

site-search/site-search.go, site-search/site-search_test.go
Add auth and collection headers to doGetWithAuth func
Anyone
=> Add auth and collection headers to doGetWithAuth func

cantabular/client.go, cantabular/client_test.go, dataset/data.go, go.sum, importapi/importapi.go
- Implement cantabular healthcheck
- Add `type` to dataset instance model
- (note) I tried to use the changes in the import process and I can see that the instance type is correctly used and the cantabular health check is correctly assessed.
anyone
=> Implement cantabular healthcheck and add 'type' in dataset Instance model

zebedee/client_test.go, zebedee/data.go
add around ONS property to zebedee client model
review code and test changes
anyone
=> add aroundONS property to zebedee client model

headers/headers.go, headers/headers_test.go
ID and Refresh header setters added
Anyone except me
=> New headers used for refreshing session tokens

zebedee/client.go, zebedee/client_test.go
* New published content endpoint updates
* check if CI works for build, audit and unit
* anyone not me
=> New content published endpoint updates

dataset/data.go
Client-side of [this dataset-api pr](https://github.com/ONSdigital/dp-dataset-api/pull/329)
- Make sure code changes make change
anyone
=> Add basedOn field to Version model

site-search/data.go, site-search/response_mocks/results.json
Add highlights struct to site-search response
=> Add highlights struct to site-search response

importapi/importapi.go, importapi/importapi_test.go
As part of updating dependencies for dp-cantabular- (trello card: https://trello.com/c/NxIax7FQ/5349-start-stop-consuming-on-healthy-unhealthy-for-dp-import-cantabular-dataset-8), I found a dependency with `dp-import-api`, which was only required in order to read the 'failed' state constant.
Following the same strategy that we implemented in `dataset api` client, in this PR we are creating an iota enum that matches the import api state constants.
Once this is merged, `dp-import-cantabular-dataset` will no longer require the dependency with dp-import-api go module.
- Make sure code change make sense
- Make sure unit tests changes make sense and cover the iota and its usage
anyone
=> created iota enum for import api states

zebedee/client.go, zebedee/client_test.go
This code is not needed as the content does not require this logic and its not reflected in other areas i.e. the displayed link in Babbage 
Compare to the commit which made the initial changes, 
https://github.com/ONSdigital/dp-api-clients-go/commit/893e35ac1020dc2e263bc601c03574e8503d8779
Anyone with knowledge of this area
=> reverted code changes to GetDataset

zebedee/client.go, zebedee/client_test.go
Handle collection id when requesting bulletin data
Sense check. Tests pass
Anyone
=> Handle collection id when requesting bulletin data

areas/areas.go, areas/areas_test.go, headers/headers.go, headers/headers_test.go
The areas profile needs to hit the areas profile api with an the language code via the headers.
Check that the added AcceptedLang func & tests are valid.
404 Team
=> Added localise code to request headers

areas/areas.go, areas/areas_test.go, areas/data.go
This adds a client function that gets the relations from area profiles.
Check for regression please
Team 404
=> Fixes unsigned commits

dataset/data.go
Add is_based_on field to DatasetDetails struct
Trello - https://trello.com/c/CciD70lI/5473-populate-isbasedon-during-dataset-creation-5
Confirm changes are correct
Anyone
=> add is_based_on field to dataset details struct

areas/areas.go, areas/areas_test.go, areas/data.go, areas/geo_data.go
=> #819 duplicate for merging

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/gql/data.go, cantabular/queries.go, cantabular/static_dataset.go
Implement Cantabular Search dimensions query accordingi to trello card: https://trello.com/c/Cnzykgy2/5453-get-areas-implement-endpoint-8
tested locally with a real client
anyone
=> Cantabular SearchDimensions

filterflex/client.go, filterflex/client_test.go, filterflex/config.go, filterflex/contract.go, filterflex/error.go
Added API client with first required function ForwardRequest for dp-cantabular-filter-flex-api
Check code makes sense, tests pass
Anyone
=> Add filterflex API client

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Added missing Filters field to query data and GetDimensionOptionsRequest
Check changes make sense, tests pass
Anyone
=> add missing filter struct to query data

zebedee/client.go, zebedee/client_test.go, zebedee/data.go
Add new function to get a release from Zebedee. 
This requires requesting the page description of the related data so to obtain its summary and hence adding a function to read the description from any page
Check the code, model and unit tests make sense
Anyone
=> Get release from zebedee

releasecalendar/client.go, releasecalendar/client_test.go
Add client for the release calendar API
Check code changes and tests make sense
Anyone but me
=> Add release calendar client

README.md
Add missing releasecalendar client and sort alphabetically
Sense check
Anyone
=> Add missing releasecalendar client and sort alphabetically

releasecalendar/client.go, releasecalendar/client_test.go
Update the releases endpoint URL for the release calendar client
Sense check
Anyone
=> Update releases endpoint URL

recipe/contract.go
Adding population-type to recipe model for Cantabular filter-flex journey.
Anyone.
=> Adding population type to recipe

areas/areas.go, areas/areas_test.go, areas/data.go
Unstub Areas Ancestors data
Ensure the tests pass and the code looks ok.
!me
=> unstub areas ancestry

interactives/data.go, interactives/interactives.go, interactives/interactives_test.go
Add archive files to dp-interactives-api update request
=> Update interactives models to include archive files when updating

areas/areas_test.go, areas/data.go
update areas ancestor struct
Ensure tests pass and code looks ok
!me
=> update areas ancestor struct

upload/client.go, upload/client_test.go
=> Add upload method to upload client

.gitignore, upload/README.md, upload/client.go, upload/client_test.go
=> Static File Upload Optional collection ID

filterflex/client.go, filterflex/client_test.go
Includes query params when proxying requests in the `filterflex` package.
Check code quality.
Anyone.
=> Include query params in filterflex request forwarding

interactives/data.go, interactives/interactives.go, interactives/interactives_test.go
Interactives API has been updated to accept `multipart/formdata` - this update reflects change in client.
Pull branch, add to importer via replace in go.mod and run journey.
Nimit
=> Update interactives PUT endpoint to multipart/formdata

upload/client.go, upload/client_test.go
=> Handle multi chunk uploads

cantabular/table.go, hierarchy/hierarchy_test.go, upload/client.go, upload/client_test.go, upload/errors.go
=> Handle error cases

dataset/data.go, dataset/dataset_test.go
Add unit tests for full editions api
This is just a unit test addition
@nshumoogum
=> Add tests for full editiondetails api

site-search/data.go, site-search/site-search.go, site-search/site-search_test.go
Add new GetReleases() api to site-search package for dp-search-api
visual review
Anyone
=> Add GetReleases() to the site-search api

upload/client.go, upload/client_test.go
=> Using the correct URL for new upload functionality

interactives/data.go, interactives/interactives.go, interactives/interactives_test.go
=> filter list endpoint

interactives/data.go
=> published state

filter/filter.go, filter/filter_test.go
Adds `updateDimensions` to send `PUT` requests to the filters api.
Read the code and tests.
Anyone.
=> Add updateDimensions to filters client

files/README.md, files/client.go, files/client_test.go, upload/README.md
=> Updating documentation to should instatiation for local and remote ports

upload/README.md
=> Added information on the upload metadata fields 

dataset/data.go
Update IsAreaType field to bool pointer as this was causing tests to panic in dp-import-cantabular-dataset
Approve
Anyone
=> change IsAreaType to bool pointer

areas/data.go
update AreaDetails GeometricData
Ensure the tests pass and code looks ok
!me
=> update AreaDetails GeometricData

interactives/data.go, interactives/interactives.go, interactives/interactives_test.go
update go api client to support filter associated collection
=> filter associated collection

files/client.go, files/client_test.go, files/data.go, upload/client.go
=> Add get method to files api

zebedee/client.go, zebedee/client_test.go, zebedee/data.go
=> Skip looking up filesize in Zebedee if file stored in Files API

filter/data.go
Added ID and Label to ModelDimension
The Dimension data model in filter-flex had ID and Label which was missing in api-client side
Anyone
=> Updated ModelDimension

download/download.go, files/README.md
=> Documenting files

files/README.md
=> Documenting API versioning in files client

interactives/data.go, zebedee/data.go
2 tiny model tweaks for interactives:
- add to Zebedee Collection
- add URI to Interactive
Sanity check
Anyone
=> Tweak interactives models - add to zebedee collection, add uri

dataset/dataset.go, dataset/dataset_test.go
Fix parameter issue for GET datasets. 
fix unit tests to represent & character, not ?
run make test
anyone in team b
=> fix: replace ? with & (GET datasets)

cantabular/client.go, cantabular/client_test.go, cantabular/codebook.go
Updating links for cantabular to reflect the version upgrade.
Anyone familiar with Cantabular.
=> Upgrading cantabular links to reflect version 10 of software

site-search/data.go, site-search/response_mocks/empty_results.json, site-search/response_mocks/results.json, site-search/site-search_test.go
- add `topics` in site-wide search response
- Check if the topics are added correctly with respect to https://github.com/ONSdigital/dp-search-api/blob/develop/swagger.yaml
- Anyone
=> add `topics` in search response

cantabular/client.go, cantabular/client_test.go
Added a Cantabular software version URL prefix value and a const to set its initial value.
Check change makes sense
Anyone
=> add Cantabular software version as const and value in client

filter/data.go
Add FilterByParent field to Dimension and ModelDimension structs
Trello - https://trello.com/c/RSo6KkmI/5773-update-dimension-and-modeldimension-structs-in-dp-api-clients-go-filter
Confirm changes match trello requirements
Anyone
=> add FilterByParent field

dimension/areas.go, population/area_types.go, population/areas.go, population/client.go, population/client_test.go
Introduced API client function to support getting parents for areaTypes
- All test pass 
- The response matches the end-point in dp-population-types-api
Anyone
=> Added support for areaTypesPatents

cantabular/dimensions_test.go, cantabular/queries.go
Change the place that the cantabular client logs query data (one level up)  for failed cantabular queries
look at changes 
Team B
=> feat: logging query and data in Unmarshall method

cantabular/interface.go, cantabular/mock/graphql_client.go, identity/interface.go
fix bugs arising from `go generate` updating outputs
⚠️ this PR goes into another PR'd branch: https://github.com/ONSdigital/dp-api-clients-go/pull/289
=> fix bugs arising from go generate needing to update outputs

cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/gql/data.go, cantabular/queries.go
Updated Cantabular parents query to return all parents, not just direct parent
Check change makes sense
Anyone
=> Update Cantabular parent query

cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Updated QueryGeographyDimensions to use variables(rule: true) instead of ruleBase as the latter is now deprecated.
Check changes make sense, tests pass
anyone
=> Update Geography query to use rule: true instead of ruleBase

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Updated the query to support pagination
- Test the query on graphQL 
- All tests pass
Anyone
=> Added pagination support

population/areas.go, population/client.go, population/client_test.go
Trello #5796 add method for
GET population-types/{type}/areas/{type}/area/{id}
run make test
ensure that the body of the api method is up to spec 
Team B
=> feat: (pop-types-api) get area method

errors/json.go, files/client.go, files/client_test.go, upload/client.go
Add support for RegisterFile method
Tidy up the remaining methods
Eyeball
Anyone
=> add RegisterFile method to the Files API client

files/client.go, files/client_test.go
Add support for patch file endpoint of the Files API
Eyeball
Anyone
=> add support for patch file endpoint of the Files API

files/data.go
A cosmetic change - mark some file metadata fields as omitempty, so that they don't appear in RegisterFile payload
Eyeball
Anyone
=> mark some file metadata fields as omitempty

population/client.go
Fix bug where Cantabular/GetArea would be responding with an empty struct as it was attempting to unmarshal the response from the service into an incorrect object.
There was not an error being returned because the response would be valid JSON, just the provided fields where incorrect.
Check the changes make sense. 
Anyone
=> Cantabular - unmarshal into correct GetAreaResponse object

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Add query and function for GetAreaParentCount
Check change makes sense
Anyone
=> Cantabular - Add GetParentAreaCount

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
[5802 Add Pagination Params on GET Areas response](https://github.com/ONSdigital/dp-api-clients-go/commit/6729d44eb4bb2635304fe681e571c4d10f1b5469)
Sense Check and review this [PR](https://github.com/ONSdigital/dp-population-types-api/pull/63).
=> 5802 Add Pagination Params on GET Areas response

cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Resolves: [5802](https://trello.com/c/7MD0oUPR/5802-bug-fix-count-on-review-page)
Sense check it and tests are green
=> 5802 Fix GetAreas 'totalCount' and 'count'

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Add dp-api-clients-go function for GET /population-types/{population-type}/dimensions/{dimension}/categorisations
Trello - https://trello.com/c/5Ltsbl56/5834-add-dp-api-clients-go-function-for-get-population-types-population-type-dimensions-dimension-categorisations
Confirm changes match requested changes in Trello ticket
Anyone
=> #5384 add GetCategorisations function

cantabularmetadata/classification.go, cantabularmetadata/classification_test.go, cantabularmetadata/client.go, cantabularmetadata/client_test.go, cantabularmetadata/config.go, cantabularmetadata/contract.go, cantabularmetadata/error.go, cantabularmetadata/interface.go, cantabularmetadata/mock/response.go, cantabularmetadata/query.go, cantabularmetadata/query_test.go
Added cantabular metadata client
Added first func, GetDefaultClassification
Anyone
=> create cantabular metadata client and GetDefaultClassification func

cantabular/contract.go, cantabular/dimensions.go, cantabular/queries.go
Update request body and alter graphql query
to match schema.
check the code. 
Team b
=> fix: cantabular GetCategorisations method

cantabular/queries.go, cantabular/static_dataset.go, cantabular/static_dataset_test.go
Fix the StaticDatasetQuery() function:
Remove the use of the `githubcom/shurcooL/graphql` external library, and instead use standard query mechanism.
Review code and ensure tests pass
Anyone
=> Fix StaticDatasetQuery()

population/client.go, population/client_test.go
Ticket : https://trello.com/c/WjjMrc4r/5865-add-pagination-parameters-to-api-clients-go-for-getareas
Added pagination support for GetAreas via API client
All test pass :green_circle: 
Anyone
=> added support for pagination

dataset/data.go
A version history of cantabular datasets is needed for the metadata tab in the xlsx download file - https://trello.com/c/V5Nffufg/5900-update-xls-meta-data-tab-to-include-additional-meta-data-fields 
`VersionsList` has been added to the `DatasetDetails` model, which is part of the `Metadata` model
Confirm changes make sense
Anyone
=> add VersionsList to DatasetDetails model

cantabular/dimensions_test.go, cantabular/gql/data.go, cantabular/queries.go
Add description field to GetGeographyDimensions query
Anyone
=> add description to cantabular/GetGeographyDimensions

dataset/data.go
Adds quality statement fields to dataset VersionDimension model to support Cantabular metadata journey.
Read the code.
Anyone
=> adds quality statement fields to VersionDimension model

cantabular/queries.go, population/area_types.go
add description to area types 
check that the struct is appropriately changes 
team b
=> feature: description to area types

dataset/data.go, dataset/data_test.go
Add `LowestGeography` to `DatasetDetails` model
Trello - https://trello.com/c/grBHtxzC/5922-update-dp-api-clients-go-to-include-new-lowestgeography-field
Confirm changes match those requested in Trello ticket
Anyone
=> add lowest_geography to dataset model

dataset/data.go, recipe/contract.go, recipe/recipe_test.go
Add lowest_geography to instance and recipe
Anyone
=> add lowest_geography to recipe and instance

cantabular/dimensions_test.go, cantabular/queries.go
Update dimensions query to include description field 
Trello - https://trello.com/c/LryLDeBf/5940-add-meta-data-to-variable-description
Confirm changes match requested changes in Trello ticket
Anyone
=> add description field

population/dimensions.go, population/dimensions_test.go
Use ID instead of Name in Dimension and GetBaseVariableResponse
Anyone
=> Use ID instead of Name for Dimension

population/dimensions.go, population/dimensions_test.go
Add `Description` to `Dimensions` model 
Confirm model has been updated correctly, tests pass
Anyone
=> add description to dimensions model

dataset/dataset.go
Slice element deletion causing panic when deleting due to modification of slice we're iterating over. Replaced with a reverse loop that doesn't have this problem. 
Ensure tests pass and code is sensible.
Anyone but me
=> Fix index out of bounds issue with deleting slice elements

cantabular/queries.go
Adding totalCount to Cantabular GetCategorisations query.
Ensure the tests pass and the changes make sense.
Anyone.
=> Adding totalCount to GetCategorisations query

population/dimensions.go
Using ID rather than code for categories response.
Ensure the tests pass and the changes make sense.
Anyone.
=> Using id rather than code for categories response

cantabular/gql/data.go, cantabular/queries.go
Updating cantabular queries for area-types to include the geography hierarchy order.
Ensure the changes make sense and the tests pass.
Anyone.
=> update queries to include order information

population/area_types.go
Adding hierarchy_order to GetAreaTypes response.
Ensure the changes make sense and the tests pass.
Anyone.
=> Adding hierarchy_order to area-types response

population/area_types.go
Change type of hierarchy_order to int
Check code
Tests pass.
!me
=>  Change type of hierarchy_order to int

cantabular/contract.go, cantabular/dataset_list.go, cantabular/dataset_list_test.go, cantabular/gql/data.go, cantabular/queries.go
Re-implement ListDatasets to include label along with name.
Switches to the more common style of GraphQL queries throughout the library.
Anyone
=> cantabular/re-implement ListDatasets to include label

filter/data.go
Add default categorisation to add dimension response
=> patch: default categorisation on filter dimension

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go, population/client.go, population/dimensions.go, population/dimensions_test.go
Implemented a api client function to return descriptions of passed dimensions
All tests are :green_circle: 
Anyone
=> Added support for dimensions description

cantabular/dimensions_test.go, cantabular/queries.go, population/dimensions.go, population/dimensions_test.go
Add QualityStatementText to categorisations query
Trello - https://trello.com/c/Y8ry9MDz/5992-add-quality-statement-text-to-get-population-types-population-type-dimensions-dimension-categorisations-response
Confirm changes match the requested changes in Trello ticket
Anyone
=> add quality statement text to categorisations

population/dimensions.go, population/dimensions_test.go
Client method for population types api added
=> feat: GetDimensionCategories client method addded

population/areas.go, population/client_test.go
Fix the api function to return the right dataset
All tests are :green_circle: 
Anyone
=> fixed the api interface

cantabular/queries.go
Attempted to remove conflicts from the QueryCategorisations query
assess whether this is the correct query
Backend go dev
=> fix merge conflict in QueryCategorisations

filter/data.go
Add `Type` to `Model`
Confirm the above has been added
Anyone
=> add Type to Model

go.mod, go.sum, population/metadata.go, population/population_type_metadata.go, population/population_type_metadata_test.go
Ticket : https://trello.com/c/ELlEBmEn/6022-create-end-point-for-new-custom-filter-flex-api
Introduced API client function to get the default dataset metadata
Anyone
=> Added GetMetadata

cantabular/gql/data.go, cantabular/queries.go
patch: add description to GET population types
=> patch: add description to GET population types

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, population/areas.go, population/client_test.go
Passing  the table level error from cantabular to FE
Anyone
=> handle cantabular table level error

population/population_types.go
ammend GetPopulationTypesResponse to include label and description
=> patch: label and description to GET population types

population/population_types.go
Added support for default dataset in api client
Anyone
=> updated to support default dataset feature

filter/filter.go, filter/filter_test.go
Added api function to create custom filter for BYO journey
Test are :green_circle: 
Anyone
=> added api function for custom filter

cantabular/queries.go
Update `QueryDimensionsByName` and `QueryNonGeoDimensionsByName` cantabular queries
Confirm changes make sense, tests pass
Anyone
=> update dimension query

cantabular/contract.go, cantabular/dimensions.go, cantabular/dimensions_test.go, cantabular/queries.go
Add GetCategorisationsCounts which returns a list of counts of categorisations for given variables
Anyone
=> cantabular/add GetCategorisationsCounts

population/client_test.go, population/population_types.go
Added population/GetPopulationType which calls GET dp-population-types-api /population-types/{population-type}
Anyone
=> population/add GetPopulationType

population/dimensions.go
Adding default categorisation flag to GetCategorisations response.
Ensure the tests pass and the changes make sense.
Anyone.
=> Adding default categrisation flag to GetCategorisations

cantabular/client.go, cantabular/static_dataset.go, cantabular/static_dataset_test.go
Handle errors from dataset.Table. Either return full string or lookup from table depending.
Anyonne
=> cantabular - handle errors from dataset.table

cantabular/queries.go
Removed the SDC calculations from static dataset query to see if this is causing the memory issues with cantabular.
Anyone.
=> Removing SDC count from cantabular query to check if this is the issue

cantabular/queries.go
Reinstating SDC query to see if this still affects the loading of the dataset landing page.
Ensure the changes make sense and the tests pass.
Anyone.
=> Reinstating SDC query to test if it still breaks things

population/population_types.go
Increase default limit on GetPopulationTypes response
Sense check
!me
=> Increase default limit on GetPopulationTypes response

go.mod, go.sum, population/client_test.go, population/population_types.go
Fixed the passing of pagination param
Anyone
=> fixed pagination

cantabular/table.go
Fixing issue with CSV file generation for Cantabular since the static dataset query was updated to include returning rules.
Ensure the changes make sense and the tests pass.
Anyone
=> Fixing CSV export issue

filter/data.go
Add missing Quality Statement for filtered dimensions
Trello - https://trello.com/c/lymFRNNp/1646-fix-missing-quality-statements-on-byo-dataset-landing-pages
Confirm changes make sense, tests pass
Anyone
=> add quality statement to ModelDimension

cantabular/gql/data.go, cantabular/queries.go, filter/data.go
Add QualitySummaryURL to be used for filtered dimensions
Changes make sense, tests pass
Anyone
=> add quality summary url for filtered dimensions

nlp/berlin/README.md, nlp/berlin/berlin_test.go, nlp/berlin/models/models.go, nlp/berlin/options.go, nlp/category/README.md, nlp/category/options.go, nlp/main/main.go
Updated the optional params in berlin and category
Updated berlin models 
Check if it's easy to setup using the guides
linting 
anyone
=> update optional params for NLP APIs

zebedee/client.go, zebedee/client_test.go, zebedee/data.go
Add `GetPageData` func to Zebedee client
Anyone
=> Add zebedee GetPageData

files/data.go
- added bundleId into FileMetaData struct
- check if the changes are correct
anyone
=> add bundlId into FileMetaData struct
